def define_badges(b):

    # Classes
    b.add("f\0\0\0", None, "STR_CLASS_FLAG")
    b.add("m\0\0\0", None, "STR_CLASS_USAGE")
    b.add("o\0\0\0", None, "STR_CLASS_OPERATOR")
    b.add("p\0\0\0", None, "STR_CLASS_PROPULSION")

    # Modes
    b.add("mPAS", None, "STR_MODE_PAS")
    b.add("mFRE", None, "STR_MODE_FRE")
    b.add("mMIX", None, "STR_MODE_MIX")
    b.add("mEXP", None, "STR_MODE_EXP")
    b.add("mEXF", None, "STR_MODE_EXF")
    b.add("mHEF", None, "STR_MODE_HEF")

    # Country flags
    b.add("fAD ", "flag-icons/ad.svg", "STR_FLAG_AD")
    b.add("fAE ", "flag-icons/ae.svg", "STR_FLAG_AE")
    b.add("fAF ", "flag-icons/af.svg", "STR_FLAG_AF")
    b.add("fAG ", "flag-icons/ag.svg", "STR_FLAG_AG")
    b.add("fAI ", "flag-icons/ai.svg", "STR_FLAG_AI")
    b.add("fAL ", "flag-icons/al.svg", "STR_FLAG_AL")
    b.add("fAM ", "flag-icons/am.svg", "STR_FLAG_AM")
    b.add("fAO ", "flag-icons/ao.svg", "STR_FLAG_AO")
    b.add("fAQ ", "flag-icons/aq.svg", "STR_FLAG_AQ")
    b.add("fARA", "flag-icons/arab.svg", "STR_FLAG_ARA")
    b.add("fAR ", "flag-icons/ar.svg", "STR_FLAG_AR")
    b.add("fAS ", "flag-icons/as.svg", "STR_FLAG_AS")
    b.add("fAT ", "flag-icons/at.svg", "STR_FLAG_AT")
    b.add("fAU ", "flag-icons/au.svg", "STR_FLAG_AU")
    b.add("fAW ", "flag-icons/aw.svg", "STR_FLAG_AW")
    b.add("fAX ", "flag-icons/ax.svg", "STR_FLAG_AX")
    b.add("fAZ ", "flag-icons/az.svg", "STR_FLAG_AZ")
    b.add("fBA ", "flag-icons/ba.svg", "STR_FLAG_BA")
    b.add("fBB ", "flag-icons/bb.svg", "STR_FLAG_BB")
    b.add("fBD ", "flag-icons/bd.svg", "STR_FLAG_BD")
    b.add("fBE ", "flag-icons/be.svg", "STR_FLAG_BE")
    b.add("fBF ", "flag-icons/bf.svg", "STR_FLAG_BF")
    b.add("fBG ", "flag-icons/bg.svg", "STR_FLAG_BG")
    b.add("fBH ", "flag-icons/bh.svg", "STR_FLAG_BH")
    b.add("fBI ", "flag-icons/bi.svg", "STR_FLAG_BI")
    b.add("fBJ ", "flag-icons/bj.svg", "STR_FLAG_BJ")
    b.add("fBL ", "flag-icons/bl.svg", "STR_FLAG_BL")
    b.add("fBM ", "flag-icons/bm.svg", "STR_FLAG_BM")
    b.add("fBN ", "flag-icons/bn.svg", "STR_FLAG_BN")
    b.add("fBO ", "flag-icons/bo.svg", "STR_FLAG_BO")
    b.add("fBQ ", "flag-icons/bq.svg", "STR_FLAG_BQ")
    b.add("fBR ", "flag-icons/br.svg", "STR_FLAG_BR")
    b.add("fBS ", "flag-icons/bs.svg", "STR_FLAG_BS")
    b.add("fBT ", "flag-icons/bt.svg", "STR_FLAG_BT")
    b.add("fBV ", "flag-icons/bv.svg", "STR_FLAG_BV")
    b.add("fBW ", "flag-icons/bw.svg", "STR_FLAG_BW")
    b.add("fBY ", "flag-icons/by.svg", "STR_FLAG_BY")
    b.add("fBZ ", "flag-icons/bz.svg", "STR_FLAG_BZ")
    b.add("fCA ", "flag-icons/ca.svg", "STR_FLAG_CA")
    b.add("fCC ", "flag-icons/cc.svg", "STR_FLAG_CC")
    b.add("fCD ", "flag-icons/cd.svg", "STR_FLAG_CD")
    b.add("fCEF", "flag-icons/cefta.svg", "STR_FLAG_CEF")
    b.add("fCF ", "flag-icons/cf.svg", "STR_FLAG_CF")
    b.add("fCG ", "flag-icons/cg.svg", "STR_FLAG_CG")
    b.add("fCH ", "flag-icons/ch.svg", "STR_FLAG_CH")
    b.add("fCI ", "flag-icons/ci.svg", "STR_FLAG_CI")
    b.add("fCK ", "flag-icons/ck.svg", "STR_FLAG_CK")
    b.add("fCL ", "flag-icons/cl.svg", "STR_FLAG_CL")
    b.add("fCM ", "flag-icons/cm.svg", "STR_FLAG_CM")
    b.add("fCN ", "flag-icons/cn.svg", "STR_FLAG_CN")
    b.add("fCO ", "flag-icons/co.svg", "STR_FLAG_CO")
    b.add("fCP ", "flag-icons/cp.svg", "STR_FLAG_CP")
    b.add("fCR ", "flag-icons/cr.svg", "STR_FLAG_CR")
    b.add("fCU ", "flag-icons/cu.svg", "STR_FLAG_CU")
    b.add("fCV ", "flag-icons/cv.svg", "STR_FLAG_CV")
    b.add("fCW ", "flag-icons/cw.svg", "STR_FLAG_CW")
    b.add("fCX ", "flag-icons/cx.svg", "STR_FLAG_CX")
    b.add("fCY ", "flag-icons/cy.svg", "STR_FLAG_CY")
    b.add("fCZ ", "flag-icons/cz.svg", "STR_FLAG_CZ")
    b.add("fDE ", "flag-icons/de.svg", "STR_FLAG_DE")
    b.add("fDG ", "flag-icons/dg.svg", "STR_FLAG_DG")
    b.add("fDJ ", "flag-icons/dj.svg", "STR_FLAG_DJ")
    b.add("fDK ", "flag-icons/dk.svg", "STR_FLAG_DK")
    b.add("fDM ", "flag-icons/dm.svg", "STR_FLAG_DM")
    b.add("fDO ", "flag-icons/do.svg", "STR_FLAG_DO")
    b.add("fDZ ", "flag-icons/dz.svg", "STR_FLAG_DZ")
    b.add("fEAC", "flag-icons/eac.svg", "STR_FLAG_EAC")
    b.add("fEC ", "flag-icons/ec.svg", "STR_FLAG_EC")
    b.add("fEE ", "flag-icons/ee.svg", "STR_FLAG_EE")
    b.add("fEG ", "flag-icons/eg.svg", "STR_FLAG_EG")
    b.add("fEH ", "flag-icons/eh.svg", "STR_FLAG_EH")
    b.add("fER ", "flag-icons/er.svg", "STR_FLAG_ER")
    b.add("fESC", "flag-icons/es-ct.svg", "STR_FLAG_ESC")
    b.add("fESG", "flag-icons/es-ga.svg", "STR_FLAG_ESG")
    b.add("fESP", "flag-icons/es-pv.svg", "STR_FLAG_ESP")
    b.add("fES ", "flag-icons/es.svg", "STR_FLAG_ES")
    b.add("fET ", "flag-icons/et.svg", "STR_FLAG_ET")
    b.add("fEU ", "flag-icons/eu.svg", "STR_FLAG_EU")
    b.add("fFI ", "flag-icons/fi.svg", "STR_FLAG_FI")
    b.add("fFJ ", "flag-icons/fj.svg", "STR_FLAG_FJ")
    b.add("fFK ", "flag-icons/fk.svg", "STR_FLAG_FK")
    b.add("fFM ", "flag-icons/fm.svg", "STR_FLAG_FM")
    b.add("fFO ", "flag-icons/fo.svg", "STR_FLAG_FO")
    b.add("fFR ", "flag-icons/fr.svg", "STR_FLAG_FR")
    b.add("fGA ", "flag-icons/ga.svg", "STR_FLAG_GA")
    b.add("fGBE", "flag-icons/gb-eng.svg", "STR_FLAG_GBE")
    b.add("fGBN", "flag-icons/gb-nir.svg", "STR_FLAG_GBN")
    b.add("fGBS", "flag-icons/gb-sct.svg", "STR_FLAG_GBS")
    b.add("fGB ", "flag-icons/gb.svg", "STR_FLAG_GB")
    b.add("fGBW", "flag-icons/gb-wls.svg", "STR_FLAG_GBW")
    b.add("fGD ", "flag-icons/gd.svg", "STR_FLAG_GD")
    b.add("fGE ", "flag-icons/ge.svg", "STR_FLAG_GE")
    b.add("fGF ", "flag-icons/gf.svg", "STR_FLAG_GF")
    b.add("fGG ", "flag-icons/gg.svg", "STR_FLAG_GG")
    b.add("fGH ", "flag-icons/gh.svg", "STR_FLAG_GH")
    b.add("fGI ", "flag-icons/gi.svg", "STR_FLAG_GI")
    b.add("fGL ", "flag-icons/gl.svg", "STR_FLAG_GL")
    b.add("fGM ", "flag-icons/gm.svg", "STR_FLAG_GM")
    b.add("fGN ", "flag-icons/gn.svg", "STR_FLAG_GN")
    b.add("fGP ", "flag-icons/gp.svg", "STR_FLAG_GP")
    b.add("fGQ ", "flag-icons/gq.svg", "STR_FLAG_GQ")
    b.add("fGR ", "flag-icons/gr.svg", "STR_FLAG_GR")
    b.add("fGS ", "flag-icons/gs.svg", "STR_FLAG_GS")
    b.add("fGT ", "flag-icons/gt.svg", "STR_FLAG_GT")
    b.add("fGU ", "flag-icons/gu.svg", "STR_FLAG_GU")
    b.add("fGW ", "flag-icons/gw.svg", "STR_FLAG_GW")
    b.add("fGY ", "flag-icons/gy.svg", "STR_FLAG_GY")
    b.add("fHK ", "flag-icons/hk.svg", "STR_FLAG_HK")
    b.add("fHM ", "flag-icons/hm.svg", "STR_FLAG_HM")
    b.add("fHN ", "flag-icons/hn.svg", "STR_FLAG_HN")
    b.add("fHR ", "flag-icons/hr.svg", "STR_FLAG_HR")
    b.add("fHT ", "flag-icons/ht.svg", "STR_FLAG_HT")
    b.add("fHU ", "flag-icons/hu.svg", "STR_FLAG_HU")
    b.add("fIC ", "flag-icons/ic.svg", "STR_FLAG_IC")
    b.add("fID ", "flag-icons/id.svg", "STR_FLAG_ID")
    b.add("fIE ", "flag-icons/ie.svg", "STR_FLAG_IE")
    b.add("fIL ", "flag-icons/il.svg", "STR_FLAG_IL")
    b.add("fIM ", "flag-icons/im.svg", "STR_FLAG_IM")
    b.add("fIN ", "flag-icons/in.svg", "STR_FLAG_IN")
    b.add("fIO ", "flag-icons/io.svg", "STR_FLAG_IO")
    b.add("fIQ ", "flag-icons/iq.svg", "STR_FLAG_IQ")
    b.add("fIR ", "flag-icons/ir.svg", "STR_FLAG_IR")
    b.add("fIS ", "flag-icons/is.svg", "STR_FLAG_IS")
    b.add("fIT ", "flag-icons/it.svg", "STR_FLAG_IT")
    b.add("fJE ", "flag-icons/je.svg", "STR_FLAG_JE")
    b.add("fJM ", "flag-icons/jm.svg", "STR_FLAG_JM")
    b.add("fJO ", "flag-icons/jo.svg", "STR_FLAG_JO")
    b.add("fJP ", "flag-icons/jp.svg", "STR_FLAG_JP")
    b.add("fKE ", "flag-icons/ke.svg", "STR_FLAG_KE")
    b.add("fKG ", "flag-icons/kg.svg", "STR_FLAG_KG")
    b.add("fKH ", "flag-icons/kh.svg", "STR_FLAG_KH")
    b.add("fKI ", "flag-icons/ki.svg", "STR_FLAG_KI")
    b.add("fKM ", "flag-icons/km.svg", "STR_FLAG_KM")
    b.add("fKN ", "flag-icons/kn.svg", "STR_FLAG_KN")
    b.add("fKP ", "flag-icons/kp.svg", "STR_FLAG_KP")
    b.add("fKR ", "flag-icons/kr.svg", "STR_FLAG_KR")
    b.add("fKW ", "flag-icons/kw.svg", "STR_FLAG_KW")
    b.add("fKY ", "flag-icons/ky.svg", "STR_FLAG_KY")
    b.add("fKZ ", "flag-icons/kz.svg", "STR_FLAG_KZ")
    b.add("fLA ", "flag-icons/la.svg", "STR_FLAG_LA")
    b.add("fLB ", "flag-icons/lb.svg", "STR_FLAG_LB")
    b.add("fLC ", "flag-icons/lc.svg", "STR_FLAG_LC")
    b.add("fLI ", "flag-icons/li.svg", "STR_FLAG_LI")
    b.add("fLK ", "flag-icons/lk.svg", "STR_FLAG_LK")
    b.add("fLR ", "flag-icons/lr.svg", "STR_FLAG_LR")
    b.add("fLS ", "flag-icons/ls.svg", "STR_FLAG_LS")
    b.add("fLT ", "flag-icons/lt.svg", "STR_FLAG_LT")
    b.add("fLU ", "flag-icons/lu.svg", "STR_FLAG_LU")
    b.add("fLV ", "flag-icons/lv.svg", "STR_FLAG_LV")
    b.add("fLY ", "flag-icons/ly.svg", "STR_FLAG_LY")
    b.add("fMA ", "flag-icons/ma.svg", "STR_FLAG_MA")
    b.add("fMC ", "flag-icons/mc.svg", "STR_FLAG_MC")
    b.add("fMD ", "flag-icons/md.svg", "STR_FLAG_MD")
    b.add("fME ", "flag-icons/me.svg", "STR_FLAG_ME")
    b.add("fMF ", "flag-icons/mf.svg", "STR_FLAG_MF")
    b.add("fMG ", "flag-icons/mg.svg", "STR_FLAG_MG")
    b.add("fMH ", "flag-icons/mh.svg", "STR_FLAG_MH")
    b.add("fMK ", "flag-icons/mk.svg", "STR_FLAG_MK")
    b.add("fML ", "flag-icons/ml.svg", "STR_FLAG_ML")
    b.add("fMM ", "flag-icons/mm.svg", "STR_FLAG_MM")
    b.add("fMN ", "flag-icons/mn.svg", "STR_FLAG_MN")
    b.add("fMO ", "flag-icons/mo.svg", "STR_FLAG_MO")
    b.add("fMP ", "flag-icons/mp.svg", "STR_FLAG_MP")
    b.add("fMQ ", "flag-icons/mq.svg", "STR_FLAG_MQ")
    b.add("fMR ", "flag-icons/mr.svg", "STR_FLAG_MR")
    b.add("fMS ", "flag-icons/ms.svg", "STR_FLAG_MS")
    b.add("fMT ", "flag-icons/mt.svg", "STR_FLAG_MT")
    b.add("fMU ", "flag-icons/mu.svg", "STR_FLAG_MU")
    b.add("fMV ", "flag-icons/mv.svg", "STR_FLAG_MV")
    b.add("fMW ", "flag-icons/mw.svg", "STR_FLAG_MW")
    b.add("fMX ", "flag-icons/mx.svg", "STR_FLAG_MX")
    b.add("fMY ", "flag-icons/my.svg", "STR_FLAG_MY")
    b.add("fMZ ", "flag-icons/mz.svg", "STR_FLAG_MZ")
    b.add("fNA ", "flag-icons/na.svg", "STR_FLAG_NA")
    b.add("fNC ", "flag-icons/nc.svg", "STR_FLAG_NC")
    b.add("fNE ", "flag-icons/ne.svg", "STR_FLAG_NE")
    b.add("fNF ", "flag-icons/nf.svg", "STR_FLAG_NF")
    b.add("fNG ", "flag-icons/ng.svg", "STR_FLAG_NG")
    b.add("fNI ", "flag-icons/ni.svg", "STR_FLAG_NI")
    b.add("fNL ", "flag-icons/nl.svg", "STR_FLAG_NL")
    b.add("fNO ", "flag-icons/no.svg", "STR_FLAG_NO")
    b.add("fNP ", "flag-icons/np.svg", "STR_FLAG_NP")
    b.add("fNR ", "flag-icons/nr.svg", "STR_FLAG_NR")
    b.add("fNU ", "flag-icons/nu.svg", "STR_FLAG_NU")
    b.add("fNZ ", "flag-icons/nz.svg", "STR_FLAG_NZ")
    b.add("fOM ", "flag-icons/om.svg", "STR_FLAG_OM")
    b.add("fPA ", "flag-icons/pa.svg", "STR_FLAG_PA")
    b.add("fPC ", "flag-icons/pc.svg", "STR_FLAG_PC")
    b.add("fPE ", "flag-icons/pe.svg", "STR_FLAG_PE")
    b.add("fPF ", "flag-icons/pf.svg", "STR_FLAG_PF")
    b.add("fPG ", "flag-icons/pg.svg", "STR_FLAG_PG")
    b.add("fPH ", "flag-icons/ph.svg", "STR_FLAG_PH")
    b.add("fPK ", "flag-icons/pk.svg", "STR_FLAG_PK")
    b.add("fPL ", "flag-icons/pl.svg", "STR_FLAG_PL")
    b.add("fPM ", "flag-icons/pm.svg", "STR_FLAG_PM")
    b.add("fPN ", "flag-icons/pn.svg", "STR_FLAG_PN")
    b.add("fPR ", "flag-icons/pr.svg", "STR_FLAG_PR")
    b.add("fPS ", "flag-icons/ps.svg", "STR_FLAG_PS")
    b.add("fPT ", "flag-icons/pt.svg", "STR_FLAG_PT")
    b.add("fPW ", "flag-icons/pw.svg", "STR_FLAG_PW")
    b.add("fPY ", "flag-icons/py.svg", "STR_FLAG_PY")
    b.add("fQA ", "flag-icons/qa.svg", "STR_FLAG_QA")
    b.add("fRE ", "flag-icons/re.svg", "STR_FLAG_RE")
    b.add("fRO ", "flag-icons/ro.svg", "STR_FLAG_RO")
    b.add("fRS ", "flag-icons/rs.svg", "STR_FLAG_RS")
    b.add("fRU ", "flag-icons/ru.svg", "STR_FLAG_RU")
    b.add("fRW ", "flag-icons/rw.svg", "STR_FLAG_RW")
    b.add("fSA ", "flag-icons/sa.svg", "STR_FLAG_SA")
    b.add("fSB ", "flag-icons/sb.svg", "STR_FLAG_SB")
    b.add("fSC ", "flag-icons/sc.svg", "STR_FLAG_SC")
    b.add("fSD ", "flag-icons/sd.svg", "STR_FLAG_SD")
    b.add("fSE ", "flag-icons/se.svg", "STR_FLAG_SE")
    b.add("fSG ", "flag-icons/sg.svg", "STR_FLAG_SG")
    b.add("fSHA", "flag-icons/sh-ac.svg", "STR_FLAG_SHA")
    b.add("fSHH", "flag-icons/sh-hl.svg", "STR_FLAG_SHH")
    b.add("fSH ", "flag-icons/sh.svg", "STR_FLAG_SH")
    b.add("fSHT", "flag-icons/sh-ta.svg", "STR_FLAG_SHT")
    b.add("fSI ", "flag-icons/si.svg", "STR_FLAG_SI")
    b.add("fSJ ", "flag-icons/sj.svg", "STR_FLAG_SJ")
    b.add("fSK ", "flag-icons/sk.svg", "STR_FLAG_SK")
    b.add("fSL ", "flag-icons/sl.svg", "STR_FLAG_SL")
    b.add("fSM ", "flag-icons/sm.svg", "STR_FLAG_SM")
    b.add("fSN ", "flag-icons/sn.svg", "STR_FLAG_SN")
    b.add("fSO ", "flag-icons/so.svg", "STR_FLAG_SO")
    b.add("fSR ", "flag-icons/sr.svg", "STR_FLAG_SR")
    b.add("fSS ", "flag-icons/ss.svg", "STR_FLAG_SS")
    b.add("fST ", "flag-icons/st.svg", "STR_FLAG_ST")
    b.add("fSV ", "flag-icons/sv.svg", "STR_FLAG_SV")
    b.add("fSX ", "flag-icons/sx.svg", "STR_FLAG_SX")
    b.add("fSY ", "flag-icons/sy.svg", "STR_FLAG_SY")
    b.add("fSZ ", "flag-icons/sz.svg", "STR_FLAG_SZ")
    b.add("fTC ", "flag-icons/tc.svg", "STR_FLAG_TC")
    b.add("fTD ", "flag-icons/td.svg", "STR_FLAG_TD")
    b.add("fTF ", "flag-icons/tf.svg", "STR_FLAG_TF")
    b.add("fTG ", "flag-icons/tg.svg", "STR_FLAG_TG")
    b.add("fTH ", "flag-icons/th.svg", "STR_FLAG_TH")
    b.add("fTJ ", "flag-icons/tj.svg", "STR_FLAG_TJ")
    b.add("fTK ", "flag-icons/tk.svg", "STR_FLAG_TK")
    b.add("fTL ", "flag-icons/tl.svg", "STR_FLAG_TL")
    b.add("fTM ", "flag-icons/tm.svg", "STR_FLAG_TM")
    b.add("fTN ", "flag-icons/tn.svg", "STR_FLAG_TN")
    b.add("fTO ", "flag-icons/to.svg", "STR_FLAG_TO")
    b.add("fTR ", "flag-icons/tr.svg", "STR_FLAG_TR")
    b.add("fTT ", "flag-icons/tt.svg", "STR_FLAG_TT")
    b.add("fTV ", "flag-icons/tv.svg", "STR_FLAG_TV")
    b.add("fTW ", "flag-icons/tw.svg", "STR_FLAG_TW")
    b.add("fTZ ", "flag-icons/tz.svg", "STR_FLAG_TZ")
    b.add("fUA ", "flag-icons/ua.svg", "STR_FLAG_UA")
    b.add("fUG ", "flag-icons/ug.svg", "STR_FLAG_UG")
    b.add("fUM ", "flag-icons/um.svg", "STR_FLAG_UM")
    b.add("fUN ", "flag-icons/un.svg", "STR_FLAG_UN")
    b.add("fUS ", "flag-icons/us.svg", "STR_FLAG_US")
    b.add("fUY ", "flag-icons/uy.svg", "STR_FLAG_UY")
    b.add("fUZ ", "flag-icons/uz.svg", "STR_FLAG_UZ")
    b.add("fVA ", "flag-icons/va.svg", "STR_FLAG_VA")
    b.add("fVC ", "flag-icons/vc.svg", "STR_FLAG_VC")
    b.add("fVE ", "flag-icons/ve.svg", "STR_FLAG_VE")
    b.add("fVG ", "flag-icons/vg.svg", "STR_FLAG_VG")
    b.add("fVI ", "flag-icons/vi.svg", "STR_FLAG_VI")
    b.add("fVN ", "flag-icons/vn.svg", "STR_FLAG_VN")
    b.add("fVU ", "flag-icons/vu.svg", "STR_FLAG_VU")
    b.add("fWF ", "flag-icons/wf.svg", "STR_FLAG_WF")
    b.add("fWS ", "flag-icons/ws.svg", "STR_FLAG_WS")
    b.add("fXK ", "flag-icons/xk.svg", "STR_FLAG_XK")
    b.add("fXX ", "flag-icons/xx.svg", "STR_FLAG_XX")
    b.add("fYE ", "flag-icons/ye.svg", "STR_FLAG_YE")
    b.add("fYT ", "flag-icons/yt.svg", "STR_FLAG_YT")
    b.add("fZA ", "flag-icons/za.svg", "STR_FLAG_ZA")
    b.add("fZM ", "flag-icons/zm.svg", "STR_FLAG_ZM")
    b.add("fZW ", "flag-icons/zw.svg", "STR_FLAG_ZW")
